const codeMappings = {
    0: "Clear sky",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Overcast",
    4: "Precipitation; reduced visibility",
    5: "Mist; visibility ≥ 1 km",
    6: "Fog; visibility < 1 km",
    7: "Non-reaching precipitation",
    8: "Showers (rain or mixed)",
    9: "Rain",
    10: "Rain showers",
    11: "Showers of rain and snow.",
    12: "Showers of snow.",
    13: "Snowfall.",
    14: "Intermittent snowfall.",
    15: "Continuous snowfall.",
    16: "Showers of rain and snow mixed.",
    17: "Showers of snow pellets.",
    18: "Showers of snow grains.",
    19: "Showers of ice pellets.",
    20: "Ice pellets.",
    21: "Showers of hail.",
    22: "Hail.",
    23: "Small hail.",
    24: "Rime.",
    25: "Glaze.",
    26: "Ice.",
    27: "Diamond dust.",
    28: "Snow grains.",
    29: "Ice pellets.",
    30: "Mist.",
    31: "Fog.",
    32: "Freezing fog.",
    33: "Shallow fog.",
    34: "Partial fog.",
    35: "Patches of fog.",
    36: "Ice fog.",
    37: "Diamond dust fog.",
    38: "Frost fog.",
    39: "Precipitation fog.",
    40: "Precipitation fog and fog.",
    41: "Drizzle.",
    42: "Rain showers.",
    43: "Intermittent rain.",
    44: "Continuous rain.",
    45: "Intermittent rain, thunderstorm in vicinity.",
    46: "Continuous rain, thunderstorm in vicinity.",
    47: "Intermittent snow, thunderstorm in vicinity.",
    48: "Continuous snow, thunderstorm in vicinity.",
    49: "Intermittent rain or snow, thunderstorm in vicinity.",
    50: "Drizzle, fog.",
    51: "Rain showers, fog.",
    52: "Intermittent rain, fog.",
    53: "Continuous rain, fog.",
    54: "Intermittent snow, fog.",
    55: "Continuous snow, fog.",
    56: "Intermittent rain or snow, fog.",
    57: "Rain, drizzle, fog.",
    58: "Intermittent rain, drizzle, fog.",
    59: "Continuous rain, drizzle, fog.",
    60: "Hail, fog.",
    61: "Rain showers, thunderstorm.",
    62: "Intermittent rain, thunderstorm.",
    63: "Continuous rain, thunderstorm.",
    64: "Intermittent snow, thunderstorm.",
    65: "Continuous snow, thunderstorm.",
    66: "Intermittent rain or snow, thunderstorm.",
    67: "Rain, drizzle, thunderstorm.",
    68: "Intermittent rain, drizzle, thunderstorm.",
    69: "Continuous rain, drizzle, thunderstorm.",
    70: "Hail, thunderstorm.",
    71: "Rain showers, snow showers.",
    72: "Intermittent rain, snow showers.",
    73: "Continuous rain, snow showers.",
    74: "Intermittent snow, snow showers.",
    75: "Continuous snow, snow showers.",
    76: "Intermittent rain or snow, snow showers.",
    77: "Rain, drizzle, snow showers.",
    78: "Intermittent rain, drizzle, snow showers.",
    79: "Continuous rain, drizzle, snow showers.",
    80: "Hail, snow showers.",
    81: "Rain, thunderstorm, snow showers.",
    82: "Intermittent rain, thunderstorm, snow showers.",
    83: "Continuous rain, thunderstorm, snow showers.",
    84: "Intermittent snow, thunderstorm, snow showers.",
    85: "Continuous snow, thunderstorm, snow showers.",
    86: "Intermittent rain or snow, thunderstorm, snow showers.",
    87: "Rain, drizzle, thunderstorm, snow showers.",
    88: "Intermittent rain, drizzle, thunderstorm, snow showers.",
    89: "Continuous rain, drizzle, thunderstorm, snow showers.",
    90: "Hail, thunderstorm, snow showers.",
    91: "Sandstorm.",
    92: "Duststorm.",
    93: "Sand and dust whirls.",
    94: "Squalls.",
    95: "Funnel cloud.",
    96: "Dust or sandstorm.",
    97: "Blowing snow.",
    98: "Blowing sand.",
    99: "Blowing snow"
};


export default codeMappings